VALID_SCHOOLS = [
    "Acadia",
    "Alberta",
    "Algoma",
    "Bishop's",
    "Brandon",
    "Brock",
    "Calgary",
    "Cape Breton",
    "Carleton",
    "Concordia",
    "Dalhousie",
    "Guelph",
    "Lakehead",
    "Laurentian",
    "Laurier",
    "Laval",
    "Lethbridge",
    "MacEwan",
    "Manitoba",
    "McGill",
    "McMaster",
    "Memorial",
    "Mount Royal",
    "Nipissing",
    "Ontario Tech",
    "Ottawa",
    "Queen's",
    "Regina",
    "Saint Mary's",
    "Saskatchewan",
    "StFX",
    "Thompson Rivers",
    "Toronto",
    "Toronto Metropolitan",
    "Trinity Western",
    "UBC",
    "UBC Okanagan",
    "UFV",
    "UNB",
    "UNBC",
    "UPEI",
    "UQAM",
    "Victoria",
    "Waterloo",
    "Western",
    "Windsor",
    "Winnipeg",
    "York",
]

BASKETBALL_TEAM_COLUMNS = [
    "team_name",
    "points_per_game",
    "games_played",
    "total_points",
    "total_wins",
    "total_losses",
    "win_percentage",
    "total_points_against",
    "field_goal_made",
    "field_goal_attempted",
    "field_goal_percentage",
    "three_pointers_made",
    "three_point_percentage",
    "three_pointers_attempted",
    "free_throws_made",
    "free_throws_attempted",
    "free_throw_percentage",
    "offensive_rebounds_per_game",
    "defensive_rebounds_per_game",
    "total_rebounds_per_game",
    "rebound_margin",
    "assists_per_game",
    "turnovers_per_game",
    "steals_per_game",
    "blocks_per_game",
    "team_fouls_per_game",
    "offensive_efficiency",
    "defensive_efficiency",
    "net_efficiency",
    "field_goal_made_against",
    "field_goal_attempted_against",
    "field_goal_percentage_against",
    "three_pointers_made_against",
    "three_pointers_attempted_against",
    "three_point_percentage_against",
    "offensive_rebounds_per_game_against",
    "defensive_rebounds_per_game_against",
    "total_rebounds_per_game_against",
    "rebound_margin_against",
    "assists_per_game_against",
    "turnovers_per_game_against",
    "steals_per_game_against",
    "blocks_per_game_against",
    "team_fouls_per_game_against",
    "points_per_game_against",
    "net_efficiency_against",
    "conference",
]

BASKETBALL_PLAYER_COLUMNS = [
    "lastname_initials",
    "first_name",
    "school",
    "games_played",
    "games_started",
    "minutes_played",
    "field_goal_made",
    "field_goal_attempted",
    "field_goal_percentage",
    "three_pointers_made",
    "three_pointers_attempted",
    "three_pointers_percentage",
    "free_throws_made",
    "free_throws_attempted",
    "free_throws_percentage",
    "total_points",
    "offensive_rebounds",
    "defensive_rebounds",
    "total_rebounds",
    "assists",
    "turnovers",
    "assist_to_turnover_ratio",
    "steals",
    "blocks",
    "personal_fouls",
    "disqualifications",
]

# Table names
BASKETBALL_MEN_TEAM_REG = "basketball_men_team_regular"
BASKETBALL_WOMEN_TEAM_REG = "basketball_women_team_regular"
BASKETBALL_MEN_PLAYERS_REG = "basketball_men_players_regular"
BASKETBALL_WOMEN_PLAYERS_REG = "basketball_women_players_regular"
