"""Contains import constant values needed for all leagues"""

BASKETBALL = "basketball"
FOOTBALL = "football"
ICE_HOCKEY = "ice_hockey"
SOCCER = "soccer"
VOLLEYBALL = "volleyball"

VALID_USPORTS_SCHOOLS = [
    "Acadia",
    "Alberta",
    "Algoma",
    "Bishop's",
    "Brandon",
    "Brock",
    "Calgary",
    "Cape Breton",
    "Carleton",
    "Concordia",
    "Dalhousie",
    "ETS",
    "Guelph",
    "Lakehead",
    "Laurentian",
    "Laurier",
    "Laval",
    "Lethbridge",
    "MacEwan",
    "Manitoba",
    "McGill",
    "McMaster",
    "Memorial",
    "Moncton",
    "Montreal",
    "Mount Allison",
    "Mount Royal",
    "Nipissing",
    "Ontario Tech",
    "Ottawa",
    "Queen's",
    "Regina",
    "RMC",
    "Saint Mary's",
    "Saskatchewan",
    "Sherbrooke",
    "StFX",
    "St. Thomas",
    "Thompson Rivers",
    "Toronto",
    "Toronto Metropolitan",
    "Trent",
    "Trinity Western",
    "UBC",
    "UBCO",
    "UBC Okanagan",
    "UFV",
    "UNB",
    "UNBC",
    "UPEI",
    "UQAM",
    "UQAC",
    "UQTR",
    "Victoria",
    "Waterloo",
    "Western",
    "Windsor",
    "Winnipeg",
    "York",
]
