name: Populate Database

on:
  schedule:
    - cron: "0 4,16,21 * 10,11,12,1,2,3 *" # Daily at 4am, 4pm, 9pm UTC from Oct to Mar

  workflow_dispatch: # Allows manual runs

jobs:
  update-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "poetry"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Print Python Version
        run: poetry run python --version

      - name: Install Dependencies
        run: poetry install --no-root --without dev

      - name: Run update script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          LOGFIRE_TOKEN: ${{ secrets.LOGFIRE_TOKEN }}
          LOG_LEVEL: INFO
          PYTHONPATH: "./"
        run: poetry run python scripts/update_all_usports_db.py
